# Path helps create a reliable path to the Chroma database folder.
from pathlib import Path
# uuid4 creates a unique ID for each user's conversation.
from uuid import uuid4

# Streamlit creates the chatbot web interface.
import streamlit as st
# load_dotenv loads secrets, such as OPENAI_API_KEY, from the .env file.
from dotenv import load_dotenv
# create_agent combines an LLM, tools, instructions, and memory.
from langchain.agents import create_agent
# init_chat_model creates the connection to the selected chat model.
from langchain.chat_models import init_chat_model
# Chroma connects to the stored vector database.
from langchain_chroma import Chroma
# AIMessage lets us identify messages generated by the LLM.
from langchain_core.messages import AIMessage
# OpenAIEmbeddings converts text into vectors so Chroma can search by meaning.
from langchain_openai import OpenAIEmbeddings
# InMemorySaver stores the agent's conversation history while the app is running.
from langgraph.checkpoint.memory import InMemorySaver

# Load environment variables before creating OpenAI models.
load_dotenv()

# Build the database path relative to this file. This works no matter which
# directory is used to run the Streamlit command.
CHROMA_DIR = Path(__file__).parent / "chroma_wiki_class"


# Streamlit reruns this Python file after every user interaction.
# cache_resource creates this expensive shared resource only once per app process.
@st.cache_resource
def create_vectorstore() -> Chroma:
    """Connect to the stored cricket Wikipedia embeddings."""
    # This must be the same embedding model used when the documents were stored.
    # It converts a user's question into a vector for similarity searching.
    embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

    # Connect to the existing Chroma collection stored on disk.
    # This code reads existing embeddings; it does not add new documents.
    return Chroma(
        collection_name="wiki_cricket_info",
        embedding_function=embeddings,
        persist_directory=str(CHROMA_DIR),
    )


# Create or reuse the cached Chroma connection.
vectorstore = create_vectorstore()


def retrieve_context(query: str) -> str:
    """
    Search stored Wikipedia data and return raw context to the agent.

    This function is registered as an agent tool. The returned text is the
    RAG response, not the final answer shown to the user.
    """
    # Find the three document chunks whose meanings are closest to the query.
    results = vectorstore.similarity_search(query, k=3)

    # Each result is a Document object. Join their page_content fields into
    # one text block that the LLM can read while preparing its final answer.
    return "\n\n".join(doc.page_content for doc in results)


def create_rag_agent():
    """Create an agent with conversation memory and the RAG search tool."""
    # The LLM reasons about the question, decides when to use the RAG tool,
    # and converts retrieved raw context into a user-friendly final answer.
    llm = init_chat_model("gpt-4o", model_provider="openai")

    return create_agent(
        # The language model used by the agent.
        llm,
        # Register retrieve_context as a tool the agent is allowed to call.
        [retrieve_context],
        # Tell the agent how it should use the retrieved information.
        system_prompt=(
            "You are a cricket assistant. Always use the retrieve_context tool "
            "before answering cricket-related questions. Base answers on the "
            "retrieved context. If the context does not contain the answer, say so."
        ),
        # Store the agent's message history in memory. The same thread_id must
        # be supplied on every request for follow-up questions to use this history.
        checkpointer=InMemorySaver(),
    )


# Streamlit reruns the full script whenever the user sends a message.
# session_state keeps values available between those reruns.

# This history is used only to redraw messages in the Streamlit user interface.
if "messages" not in st.session_state:
    st.session_state.messages = []

# InMemorySaver groups conversation history by thread_id. A unique thread ID
# prevents this browser session from sharing agent memory with another session.
if "thread_id" not in st.session_state:
    st.session_state.thread_id = str(uuid4())

# Store the agent in session_state so it and its InMemorySaver are not recreated
# after every Streamlit rerun.
if "agent" not in st.session_state:
    st.session_state.agent = create_rag_agent()


# Create the visible page heading.
st.title("Cricket Wikipedia RAG Chatbot")

# Redraw previous UI messages after each Streamlit rerun.
# This is different from InMemorySaver: this list controls what users see,
# while InMemorySaver controls what previous messages the agent remembers.
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])


def generate_answer(user_input: str) -> str:
    """Call the RAG agent and display its latest AI response."""
    # This variable will hold only the final text generated by the LLM.
    assistant_response = ""

    # Create an assistant chat bubble in the Streamlit interface.
    with st.chat_message("assistant"):
        # The placeholder lets us update the same bubble as agent events arrive.
        message_placeholder = st.empty()

        # This is where the agent is called.
        #
        # During this call, the agent can:
        # 1. Read the current user message and remembered conversation.
        # 2. Call retrieve_context to search Chroma.
        # 3. Receive raw RAG context from retrieve_context.
        # 4. Ask the LLM to produce a final answer using that context.
        for event in st.session_state.agent.stream(
            # Send the current question to the agent.
            {"messages": [{"role": "user", "content": user_input}]},
            # Use the same thread ID so InMemorySaver includes earlier messages.
            {"configurable": {"thread_id": st.session_state.thread_id}},
            # Return the complete graph state after each agent step.
            stream_mode="values",
        ):
            # Events may end with a user message, an AI tool request, a raw tool
            # response, or the final AI answer. Get the newest message.
            last_message = event["messages"][-1]

            # Display only AI-generated text. This prevents raw RAG tool output
            # from being shown as if it were the final answer.
            if isinstance(last_message, AIMessage) and isinstance(
                last_message.content, str
            ):
                assistant_response = last_message.content
                message_placeholder.markdown(assistant_response)

    # Return the final answer so it can be saved in the visible UI history.
    return assistant_response


# Display the input box and wait for the user to submit a question.
prompt = st.chat_input("Ask a question about cricket")

# prompt is None until the user submits text.
if prompt:
    # Immediately display the user's submitted question.
    with st.chat_message("user"):
        st.markdown(prompt)

    # Save the question so it remains visible after the next Streamlit rerun.
    st.session_state.messages.append({"role": "user", "content": prompt})

    # Send the question to the RAG agent and receive its final answer.
    answer = generate_answer(prompt)

    # Save the final answer so it remains visible after the next rerun.
    st.session_state.messages.append({"role": "assistant", "content": answer})
